services:
  - type: web
    name: barekegn-amazon-backend
    env: node
    plan: free
    repo: https://github.com/barekegnn/Amazon-Clone-Project.git
    rootDir: Backend
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_ORIGIN
        value: https://barekegn-amazon-frontend.netlify.app
    healthCheckPath: /health
